### ISSUE TITLE
All keyboard input not working (paste, virtual keyboard, physical keyboard) after reboot

### ISSUE THREAD

**Issue by mgleason2002** [jetkvm/kvm#412]
App: 0.3.9
System: 0.2.3

Using an Minisforum MS-01 connected with USB C to A cable that came in the box. OS is Proxmox 8.3.5.

After rebooting the machine, JetKVM does not register any inputs from the Paste text box, virtual keyboard or physical keyboard.

Semi-reliable workaround has been to go to Settings > Hardware > Identifiers and select a different keyboard emulation. Sometimes it requires two or three changes to any random identifier, then all keyboard input, paste, etc will start working normally. Works while the system is up and running, has to be redone after reboot every time.

**Comment by harrywustl** [comment]
Same issue as well, with HP Z240.

**Comment by molotch** [comment]
Same problem, also running proxmox on a ASUS PN51 nuc. Had problems getting USB to be recognized in the first place, but now it says connected but no keystrokes are getting through to the OS.

**Comment by geozeke** [comment]
Had the same issue after the `0.4.1` update. Just happen to check `Settings > Keyboard`, and noticed that my keyboard layout switched from my preferred, to `Belgisch Nederlands` for some reason. Switched it back to my preferred layout, and all is well.

**Comment by molotch** [comment]
Seems to be some rolling updates. I'm still on App: 0.3.9, System: 0.2.4 and update says I'm running the latest version.

I don't even have a Settings > Keyboard setting, only mouse.

Still keyboard presses aren't going through.

**Comment by molotch** [comment]
Mine started working once I updated to 0.4.1 (you have to enable Dev Channel Updates under Advanced in settings). I use the settings Hardware -> Usb Device -> Classes: Keyboard Only and Identifier JetKVM Default.

**Comment by pessimal** [comment]
Everything was working fine yesterday, today no keyboard inputs of any kind. None of the workarounds posted here have worked so far.
App: 0.4.4
System 0.2.4

Edit: In the end I had to physically change the usb port for things to start working again, not even unbinding and rebinding the old one had any effect

**Comment by Crash1602** [comment]
Unfortunately, I’m experiencing the same issue.

App: 0.4.6
System: 0.2.5

An Intel NUC i9 13900K and a Dell Optiplex 3000 only sporadically respond to input—regardless of whether I'm using the physical or virtual keyboard. Letters, numbers, and arrow keys don't react. After rebooting the JetKVM, it works briefly, but as soon as the host reboots (e.g., during a BIOS update), the keyboard stops responding again. I had just updated from 0.3.9 to 0.4.6 shortly before. I didn’t notice these issues with version 0.3.9.

The lower bar correctly shows what’s being typed, but nothing reaches the host. I tested it with Edge Chromium and Firefox (my Main-Browser) at a Linux PC and Windows 11 PC.

**Comment by j796160836** [comment]
Maybe issue #239 is related

**Comment by rgl** [comment]
FWIW, this also happens in a Dell OptiPlex 7060 Micro. After some time, the USB keyboard stops working, and only reconnecting the USB cable makes it works again.

**Comment by joelis10** [comment]
Happens to me too and can't seem to fix it. First, keyboard went a bit spazzy with sometimes keeping a key held down for longer than I'd pressed it but now it's gone completely.

Edit: fixed by unplugging the JetKVM and plugging it back in but no idea how long it'll stay fixed for

**Comment by alexruffell** [comment]
I have 3 JetKVM units that all stopped accepting keyboard strokes at the same time. All 3 are connected to ProxMox hosts. I got one to work briefly by using incognito mode but that didn't last long.

Image because I can't copy paste the version info for some reason - annoying!

<img width="158" height="58" alt="Image" src="https://github.com/user-attachments/assets/e3cd3810-e0e5-40a2-bc80-9e5f974be173" />

**Comment by CrustyB** [comment]
Same.  all keyboard input (including the virtual keyboard) stopped working.  MS-01

**Comment by HypnoticPenguin** [comment]
Same issue here, looks like I was on the dev firmware branch which downloaded 0.4.7 which seems very unstable.  I wasnt able to select options in the gui nor would keyboard input work.

I performed a reflash using DFU mode and its resolved the issue. Instructions are here: https://jetkvm.com/docs/advanced-usage/factory-reset

After the DFU reflash I was on version 0.4.5 and then I performed an update to 0.4.6 which looks like the most recent non dev firmware. I'll be staying away from dev firmwares going forward.

**Comment by Crash1602** [comment]
I have installed App 0.4.8 and System 0.2.5, and unfortunately the issue still occurs exactly as before :-(
At first all inputs work, then I perform a restart because I want to do a BIOS update using a mounted IMG file, and immediately after this first reboot of the host the keyboard keys no longer respond—for example, I can’t open the boot menu.

**Comment by Crash1602** [comment]
I'd like to ask if the problem is still being investigated, if a solution is being worked on, or if it's still being monitored? Yesterday I had another instance where the keyboard signals weren't being transmitted to the device :-/

**Comment by eddieparker** [comment]
I was experiencing this too, until I realized that I plugged in the splitter that came with the boxes - it only gave power to the devices, but didn't provide input.

I took out the splitter, and things worked.

I couldn't find any documentation about the splitter anywhere, so I thought it was necessary.  If I had to guess, I'd probably want to plug the lightning-bolt symbol to power (i.e., a USB wall wart) and the USB symbol to thePC, my guess being that would provide me with power when the device was shutdown.

Not sure if others are experiencing this for the same reason, but thought I'd mention it.

**Comment by Crash1602** [comment]
@eddieparker 

That’s an interesting hint. I couldn’t test it myself because I don’t have a power injector or PoE, but my colleague is running this setup using a power injector via RJ45 and doesn’t have this problem. So it does seem that the USB-C splitter is causing the issue.

**Comment by angelomelonas** [comment]
I am also experiencing this issue on a Dell OptiPlex 3060 (SFF) running Proxmox. The JetKVM is powered by an external USB adapter, using the splitter cable.

The keyboard _sometimes_ works (after restarting the host), but even after trying all of the suggestions above (excluding the factory reset) I can't get it working consistently.

```
App: 0.5.1
System: 0.2.5
```

**Comment by adamshiervani** [comment]
This should be fixed in **v0.5.5** (released 2026-03-31). We merged several USB HID recovery fixes that directly address the symptom you're all seeing — keyboard input failing after the host power-cycles or reboots:

- **#1297** – auto-recover USB gadget when host power-cycles
- **#1364** – USB HID startup recovery
- **#1366** – recover HID chardev after DWC3 rebind race on RV1106
- **#1336, #1331, #1349** – additional disconnect race and goroutine leak fixes

The web UI showing keypresses correctly while nothing reached the host confirmed this was a USB HID gadget issue — the file descriptors became stale after the host's DWC3 controller detached and reattached on reboot, with no recovery path in older firmware. The new `checkUSBState()` loop monitors USB state every 500ms and automatically calls `attemptUSBRecovery()` when it detects this condition.

Please update to **0.5.5** and let us know if the issue persists. If you're still seeing it on 0.5.5+, please share your full version info and host hardware so we can investigate further.

**Comment by mikensan** [comment]
Latest update that was available to me was 5.4, I enabled the Dev Channel and was able to update to 5.6. 
To note: prior to the update my keyboard input was not working.
Post-Update to 5.6, my keybaord still does not work. I've restart 3 times to no avail. Once I'm home I will unplug / plug all USB and try again.

**Comment by Crash1602** [comment]
Good morning,

I finally had the chance to perform some tests and would like to provide positive feedback.

Both JetKVM devices are running the following versions:

- App Version: 0.5.8
- System Version: 0.2.8

I performed multiple reboots, power-offs, and boots into UEFI. I was also able to use both the virtual and physical keyboard, as well as my mouse, including within the UEFI environment. In all cases, everything worked as expected and I did not encounter any issues.

Thank you very much for your great work and continued development of this project!

**Comment by nicolo-ribaudo** [comment]
Hey I am on this version:
- App Version: 0.5.8
- System Version: 0.2.8

And I just got the same problem again. I will see if I can get some useful logs (but not now because after a few reboots of both the host and the JetKVM it now works 😅)

**Comment by Unkn0wnNPC** [comment]
Hey I am on this version:

    App Version: 0.5.9
    System Version: 0.2.8

And I just got the same problem again. It just does not work in the UEFI
